project:
  type: website

website:
  title: "Portfolio"

  navbar:
    left:
      - text: Home
        href: index.qmd

      - text: Projects
        href: en/projects.qmd

      - text: Gallery
        href: en/projects/gallery.qmd

      - text: Contact
        href: en/contact.qmd

    right:
      - text: 🌐 Language
        menu:
          - text: ᴇɴ English
            href: en/index.qmd

          - text: 🇪🇸 Español
            href: es/index.qmd

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    include-in-header:
      - text: |
          <script src="/navbar-language.js"></script>
    